// Based on https://stackoverflow.com/questions/1550249/programmatically-change-the-assemblyversion-and-assemblyfileversion-attributes
// and https://stackoverflow.com/questions/17123991/t4-reference-a-const-in-a-static-class-at-compile-time

// This is an autogenerated AssemblyInfo.cs file, it will be updated per build

using System.Reflection;
using System.Runtime.InteropServices;

using MelonLoader;
using LabFusion;

[assembly: Guid("490e160d-251d-4ab4-a3bb-f473961ff8a1")]
[assembly: AssemblyTitle("LabFusion")]
[assembly: AssemblyVersion("1.3.2")]
[assembly: AssemblyFileVersion("1.3.2")]

[assembly: MelonInfo(typeof(FusionMod), "LabFusion", "1.3.2", "Lakatrazz")]
[assembly: MelonGame("Stress Level Zero", "BONELAB")]
[assembly: MelonPriority(-10000)]
[assembly: MelonOptionalDependencies("System.Windows.Forms")]
[assembly: MelonIncompatibleAssemblies("BonelabMultiplayerMockup", "Junction")]
