name: Feature Request
description: Request a new feature for the mod
title: "[Enhancement]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature or idea
    validations:
      required: true
  - type: textarea
    id: upload
    attributes:
      label: Upload
      description: >-
        Upload any additional screenshots or media that could help explain the
        feature